### ISSUE TITLE
error using mapping custom generated by benchmark.

### ISSUE THREAD

**Issue by FrankBorrero** [oeg-upm/gtfs-bench#119]
Hi, when I'm using a mapping file custom generated by  benchmark  with the SDM tool, im getting following error:

Semantifying KGCase04.nt...

TM: http://mapping.example.com/map_calendar_date_rules_0

TM: http://mapping.example.com/map_calendar_rules_0

TM: http://mapping.example.com/map_trips_0

TM: http://mapping.example.com/map_shapes_0

TM: http://mapping.example.com/map_services2_0

TM: http://mapping.example.com/map_feed_0

TM: http://mapping.example.com/map_services1_0

TM: http://mapping.example.com/map_stoptimes_0
Traceback (most recent call last):
  File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 309, in config
    self._port = int(config['port'])
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3643, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",", output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 2055, in semantify_file
    db = connector.connect(host=host, port=port, user=user, password=password)
  File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/__init__.py", line 183, in connect
    return MySQLConnection(*args, **kwargs)
  File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 100, in __init__
    self.connect(**kwargs)
  File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 733, in connect
    self.config(**kwargs)
  File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 314, in config
    raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: TCP/IP port number should be an integer

It can be reproduced running last version from benchmark, with size 1 and following file distribution:

Custom Distribution:

? [ Custom distribution ] Select output format for AGENCY TM:  JSON
? [ Custom distribution ] Select output format for CALENDAR_DATES TM:  XML
? [ Custom distribution ] Select output format for CALENDAR TM:  CSV
? [ Custom distribution ] Select output format for FEED_INFO TM:  JSON
? [ Custom distribution ] Select output format for FREQUENCIES TM:  XML
? [ Custom distribution ] Select output format for ROUTES TM:  CSV
? [ Custom distribution ] Select output format for SHAPES TM:  JSON
? [ Custom distribution ] Select output format for STOPS TM:  XML
? [ Custom distribution ] Select output format for STOP_TIMES TM:  CSV
? [ Custom distribution ] Select output format for TRIPS TM:  JSON

 Then the mapping file is used  locally with SDM.

Im attaching the  mapping file, as also configfile used.
[Dropbox.zip](https://github.com/oeg-upm/gtfs-bench/files/5276736/Dropbox.zip)

**Comment by FrankBorrero** [comment]
I wil close this issue, and will open it on SDM repository, as i tried with RocketRML and the mapping worked, so its not a mapping problem.
